name: "CI-CD Workflow"
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Copy dist to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }} 
        source: "."
        target: "~/Project-Management-App"  
    - name: Install and start application
      uses: appleboy/ssh-action@v1.2.0  
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/Project-Management-App
          npm install
          cp .env.example .env
          php artisan key:generate
          php artisan db:seed
          npm run dev
          php artisan serve --host=0.0.0.0 --port=8000
